services:
  nginx:
    image: nginx:latest
    container_name: "nginx"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/live/***/fullchain.pem:/etc/letsencrypt/live/***/fullchain.pem
      - /etc/letsencrypt/live/***/privkey.pem:/etc/letsencrypt/live/***/privkey.pem
      - ./default.conf:/etc/nginx/conf.d/default.conf

  spring:
    image: spring:latest
    container_name: "spring"
